Error Executed at: 06-07-2024 08:37:19 AM
Error: cannot access local variable 'item_program' where it is not associated with a value

Error Executed at: 06-07-2024 08:35:24 AM
Error: cannot access local variable 'item_program' where it is not associated with a value

Error Executed at: 06-06-2024 08:25:10 AM
Error: 'datetime.datetime' object is not subscriptable

Error Executed at: 06-06-2024 08:23:06 AM
Error: 'datetime.datetime' object is not subscriptable

Error Executed at: 06-06-2024 08:22:17 AM
Error: 'datetime.datetime' object is not subscriptable

Error Executed at: 06-06-2024 08:19:55 AM
Error: '>' not supported between instances of 'tuple' and 'datetime.datetime'

Error Executed at: 06-06-2024 08:11:44 AM
Error: '<' not supported between instances of 'datetime.datetime' and 'str'

Error Executed at: 06-06-2024 08:09:03 AM
Error: '<' not supported between instances of 'datetime.datetime' and 'str'

Error Executed at: 06-05-2024 08:56:22 AM
Error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Error Executed at: 06-05-2024 08:55:45 AM
Error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Error Executed at: 05-21-2024 11:43:10 AM
Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 11:27:15 AM
Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 10:55:00 AM
Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 10:20:31 AM
Error: (pid=1380)

Error Executed at: 05-21-2024 10:20:28 AM
Error: (pid=1332)

Error Executed at: 05-21-2024 10:20:26 AM
Error: (pid=1136)

Error Executed at: 05-21-2024 10:20:24 AM
Error: (pid=1104)

Error Executed at: 05-21-2024 10:20:22 AM
Error: (pid=1032)

Error Executed at: 05-21-2024 10:20:20 AM
Error: (pid=1008)

Error Executed at: 05-21-2024 10:20:18 AM
Error: (pid=836)

Error Executed at: 05-21-2024 10:20:12 AM
Error: (pid=672)

Error Executed at: 05-21-2024 10:20:07 AM
Error: (pid=176)

Error Executed at: 05-21-2024 10:09:06 AM
Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 10:07:55 AM
Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 10:06:39 AM
Error: Permission Denied

Error Executed at: 05-21-2024 10:01:59 AM
Error: Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 09:59:51 AM
Error: Error: [WinError 32] The process cannot access the file because it is being used by another process

Error Executed at: 05-21-2024 08:04:12 AM
Error: W:\User Folders\VinhH\Python Proj\Program Mover Project\Checked Item.json
File Does Not Exist

